# Generated by Django 4.2.27 on 2026-03-14 00:00

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0119_alter_estimatepoint_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="IssueCoordinationState",
            fields=[
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("route_to", models.TextField(blank=True, null=True)),
                ("reply_identity", models.TextField(blank=True, null=True)),
                ("coordination_status", models.CharField(default="new", max_length=100)),
                ("allowed_responder", models.TextField(blank=True, null=True)),
                ("waiting_on", models.TextField(blank=True, null=True)),
                ("waiting_since", models.DateTimeField(blank=True, null=True)),
                ("claim_expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_transition_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="issuecoordinationstate_created_by", to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("updated_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="issuecoordinationstate_updated_by", to=settings.AUTH_USER_MODEL, verbose_name="Last Modified By")),
                ("approver", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="issue_coordination_approvals", to=settings.AUTH_USER_MODEL)),
                ("claimed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="issue_coordination_claims", to=settings.AUTH_USER_MODEL)),
                ("issue", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="coordination_state", to="db.issue")),
                ("last_actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="issue_coordination_actions", to=settings.AUTH_USER_MODEL)),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="project_issuecoordinationstate", to="db.project")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="workspace_issuecoordinationstate", to="db.workspace")),
            ],
            options={
                "verbose_name": "Issue Coordination State",
                "verbose_name_plural": "Issue Coordination States",
                "db_table": "issue_coordination_states",
                "ordering": ("-updated_at",),
            },
        ),
    ]
